# This file could be used for testing the API with Visual Studio Code's REST Client extension

## TEACHER LOGIN
POST http://localhost:3000/api/sessions HTTP/1.1
Content-Type: application/json

{
    "username": "rossi.marco@email.com",
    "password": "d279620"
}
###

## STUDENT LOGIN
POST http://localhost:3000/api/sessions HTTP/1.1
Content-Type: application/json

{
    "username": "rizzo.amerigo@email.com",
    "password": "s304580"
}
### 

## GET CURRENT LOGGED USER
GET http://localhost:3000/api/sessions/current HTTP/1.1
###

## LOGOUT
DELETE http://localhost:3000/api/sessions/current HTTP/1.1
###

## INSERT A NEW THESIS PROPOSAL
POST http://localhost:3000/api/teacher/thesis_proposals HTTP/1.1
Content-Type: application/json

{
  "title": "TitoloTesi",
  "supervisor_id": "d279620",
  "internal_co_supervisors_id": ["d277137"],
  "external_co_supervisors_id": ["1"],
  "type": "compilativa",
  "description": "description",
  "required_knowledge": "required knowledge",
  "notes": "notes",
  "expiration": "28/11/2023",
  "level": "Bachelor's",
  "cds" : "LM-29",
  "keywords": ["keyword"]
}
###

## GET LIST OF TEACHERS NOT LOGGED
GET http://localhost:3000/api/teachers HTTP/1.1
###

## GET LIST OF EXTERNAL CO-SUPERVISORS
GET http://localhost:3000/api/externalCoSupervisors HTTP/1.1
###

## GET ALL KEYWORDS
GET http://localhost:3000/api/keywords HTTP/1.1
###

## GET DEGREES
GET http://localhost:3000/api/degrees HTTP/1.1
###

## SEARCH FOR THESIS PROPOSALS
GET http://localhost:3000/api/thesis-proposals HTTP/1.1
###

## GET THESIS PROPOSAL BY ID (for student belonging to the same cds of the proposal)
GET http://localhost:3000/api/thesis-proposals/1 HTTP/1.1
###

## APPLY FOR THESIS PROPOSAL
POST http://localhost:3000/api/student/applications HTTP/1.1
Content-Type: application/json

{
    "thesis_proposal_id": 2
}
### 

## LIST ALL THESIS PROPOSALS OF A PROFESSOR (supervisor)
GET http://localhost:3000/api/teacher/thesis_proposals HTTP/1.1
###

## LIST ALL APPLICATIONS FOR A TEACHER'S THESIS PROPOSAL
GET http://localhost:3000/api/teacher/applications/1 HTTP/1.1
###

## FUNCTION TO GET ALL APPLICATION OF A STUDENT
GET http://localhost:3000/api/student/applications HTTP/1.1
###

## FUNCTION TO ACCEPT AN APPLICATION
PATCH http://localhost:3000/api/teacher/applications/accept/1
Content-Type: application/json

{
  "student_id": "s299119"
}

###

// FUNCTION TO REJECT ALL THE OTHER APPLICATIONS
PATCH http://localhost:3000/api/teacher/applications/reject/1
Content-Type: application/json

{
  "student_id": "s299119"
}

###