name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
        working-directory: backend
      - name: Test and coverage
        run: npm run test
        env:
          TM_DOTENV_KEY: ${{ secrets.TM_DOTENV_KEY }}
          TM_DOTENV_KEY_CI: ${{ secrets.TM_DOTENV_KEY }}
        working-directory: backend
        continue-on-error: true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
